/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApercuRouteImport } from './routes/_authenticated/apercu'
import { Route as AuthenticatedDossiersRouteImport } from './routes/_authenticated/dossiers'
import { Route as AuthenticatedEmployeurRouteImport } from './routes/_authenticated/employeur'
import { Route as AuthenticatedEntreprisesRouteImport } from './routes/_authenticated/entreprises'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as InvitationTokenRouteImport } from './routes/invitation.$token'
import { Route as SalarieTokenRouteImport } from './routes/salarie.$token'
import { Route as AuthenticatedDossiersCaseIdRouteImport } from './routes/_authenticated/dossiers_.$caseId'
import { Route as AuthenticatedParametresEquipeRouteImport } from './routes/_authenticated/parametres.equipe'
import { Route as AuthenticatedParametresImportsRouteImport } from './routes/_authenticated/parametres.imports'
import { Route as ApiPublicIngestStoppagesRouteImport } from './routes/api/public/ingest/stoppages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApercuRoute = AuthenticatedApercuRouteImport.update({
  id: '/apercu',
  path: '/apercu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersRoute = AuthenticatedDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeurRoute = AuthenticatedEmployeurRouteImport.update({
  id: '/employeur',
  path: '/employeur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntreprisesRoute =
  AuthenticatedEntreprisesRouteImport.update({
    id: '/entreprises',
    path: '/entreprises',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SalarieTokenRoute = SalarieTokenRouteImport.update({
  id: '/salarie/$token',
  path: '/salarie/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDossiersCaseIdRoute =
  AuthenticatedDossiersCaseIdRouteImport.update({
    id: '/dossiers_/$caseId',
    path: '/dossiers/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametresEquipeRoute =
  AuthenticatedParametresEquipeRouteImport.update({
    id: '/parametres/equipe',
    path: '/parametres/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParametresImportsRoute =
  AuthenticatedParametresImportsRouteImport.update({
    id: '/parametres/imports',
    path: '/parametres/imports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicIngestStoppagesRoute =
  ApiPublicIngestStoppagesRouteImport.update({
    id: '/api/public/ingest/stoppages',
    path: '/api/public/ingest/stoppages',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apercu': typeof AuthenticatedApercuRoute
  '/dossiers': typeof AuthenticatedDossiersRoute
  '/employeur': typeof AuthenticatedEmployeurRoute
  '/entreprises': typeof AuthenticatedEntreprisesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/salarie/$token': typeof SalarieTokenRoute
  '/dossiers/$caseId': typeof AuthenticatedDossiersCaseIdRoute
  '/parametres/equipe': typeof AuthenticatedParametresEquipeRoute
  '/parametres/imports': typeof AuthenticatedParametresImportsRoute
  '/api/public/ingest/stoppages': typeof ApiPublicIngestStoppagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apercu': typeof AuthenticatedApercuRoute
  '/dossiers': typeof AuthenticatedDossiersRoute
  '/employeur': typeof AuthenticatedEmployeurRoute
  '/entreprises': typeof AuthenticatedEntreprisesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/salarie/$token': typeof SalarieTokenRoute
  '/dossiers/$caseId': typeof AuthenticatedDossiersCaseIdRoute
  '/parametres/equipe': typeof AuthenticatedParametresEquipeRoute
  '/parametres/imports': typeof AuthenticatedParametresImportsRoute
  '/api/public/ingest/stoppages': typeof ApiPublicIngestStoppagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apercu': typeof AuthenticatedApercuRoute
  '/_authenticated/dossiers': typeof AuthenticatedDossiersRoute
  '/_authenticated/employeur': typeof AuthenticatedEmployeurRoute
  '/_authenticated/entreprises': typeof AuthenticatedEntreprisesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/salarie/$token': typeof SalarieTokenRoute
  '/_authenticated/dossiers_/$caseId': typeof AuthenticatedDossiersCaseIdRoute
  '/_authenticated/parametres/equipe': typeof AuthenticatedParametresEquipeRoute
  '/_authenticated/parametres/imports': typeof AuthenticatedParametresImportsRoute
  '/api/public/ingest/stoppages': typeof ApiPublicIngestStoppagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apercu'
    | '/dossiers'
    | '/employeur'
    | '/entreprises'
    | '/messages'
    | '/tableau-de-bord'
    | '/invitation/$token'
    | '/salarie/$token'
    | '/dossiers/$caseId'
    | '/parametres/equipe'
    | '/parametres/imports'
    | '/api/public/ingest/stoppages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apercu'
    | '/dossiers'
    | '/employeur'
    | '/entreprises'
    | '/messages'
    | '/tableau-de-bord'
    | '/invitation/$token'
    | '/salarie/$token'
    | '/dossiers/$caseId'
    | '/parametres/equipe'
    | '/parametres/imports'
    | '/api/public/ingest/stoppages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apercu'
    | '/_authenticated/dossiers'
    | '/_authenticated/employeur'
    | '/_authenticated/entreprises'
    | '/_authenticated/messages'
    | '/_authenticated/tableau-de-bord'
    | '/invitation/$token'
    | '/salarie/$token'
    | '/_authenticated/dossiers_/$caseId'
    | '/_authenticated/parametres/equipe'
    | '/_authenticated/parametres/imports'
    | '/api/public/ingest/stoppages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  SalarieTokenRoute: typeof SalarieTokenRoute
  ApiPublicIngestStoppagesRoute: typeof ApiPublicIngestStoppagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apercu': {
      id: '/_authenticated/apercu'
      path: '/apercu'
      fullPath: '/apercu'
      preLoaderRoute: typeof AuthenticatedApercuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers': {
      id: '/_authenticated/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof AuthenticatedDossiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employeur': {
      id: '/_authenticated/employeur'
      path: '/employeur'
      fullPath: '/employeur'
      preLoaderRoute: typeof AuthenticatedEmployeurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprises': {
      id: '/_authenticated/entreprises'
      path: '/entreprises'
      fullPath: '/entreprises'
      preLoaderRoute: typeof AuthenticatedEntreprisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salarie/$token': {
      id: '/salarie/$token'
      path: '/salarie/$token'
      fullPath: '/salarie/$token'
      preLoaderRoute: typeof SalarieTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dossiers_/$caseId': {
      id: '/_authenticated/dossiers_/$caseId'
      path: '/dossiers/$caseId'
      fullPath: '/dossiers/$caseId'
      preLoaderRoute: typeof AuthenticatedDossiersCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres/equipe': {
      id: '/_authenticated/parametres/equipe'
      path: '/parametres/equipe'
      fullPath: '/parametres/equipe'
      preLoaderRoute: typeof AuthenticatedParametresEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres/imports': {
      id: '/_authenticated/parametres/imports'
      path: '/parametres/imports'
      fullPath: '/parametres/imports'
      preLoaderRoute: typeof AuthenticatedParametresImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ingest/stoppages': {
      id: '/api/public/ingest/stoppages'
      path: '/api/public/ingest/stoppages'
      fullPath: '/api/public/ingest/stoppages'
      preLoaderRoute: typeof ApiPublicIngestStoppagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApercuRoute: typeof AuthenticatedApercuRoute
  AuthenticatedDossiersRoute: typeof AuthenticatedDossiersRoute
  AuthenticatedEmployeurRoute: typeof AuthenticatedEmployeurRoute
  AuthenticatedEntreprisesRoute: typeof AuthenticatedEntreprisesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedDossiersCaseIdRoute: typeof AuthenticatedDossiersCaseIdRoute
  AuthenticatedParametresEquipeRoute: typeof AuthenticatedParametresEquipeRoute
  AuthenticatedParametresImportsRoute: typeof AuthenticatedParametresImportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApercuRoute: AuthenticatedApercuRoute,
  AuthenticatedDossiersRoute: AuthenticatedDossiersRoute,
  AuthenticatedEmployeurRoute: AuthenticatedEmployeurRoute,
  AuthenticatedEntreprisesRoute: AuthenticatedEntreprisesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedDossiersCaseIdRoute: AuthenticatedDossiersCaseIdRoute,
  AuthenticatedParametresEquipeRoute: AuthenticatedParametresEquipeRoute,
  AuthenticatedParametresImportsRoute: AuthenticatedParametresImportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  SalarieTokenRoute: SalarieTokenRoute,
  ApiPublicIngestStoppagesRoute: ApiPublicIngestStoppagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
